# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x

      - name:  Install dependencies
        run: yarn

      - name: Create env
        run: echo "REACT_APP_API=https://www2.agendamento.pm.rn.gov.br/sispag_ws/v1/public/api/" >> .env

      - name: Run Build
        run: yarn build

      - name: Copy dist to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key:  ${{ secrets.SSH_KEY }}
          source: ".next"
          target: "apps/client"
